=== pinkou78/bbclic2020_open/published/Application Files/BBClic® 2020_2_0_0_0/data/template_save.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="root">
    	<xs:complexType>
			<xs:sequence>
				<xs:element ref="general"/>
				<xs:element ref="configuration"/>
                <xs:element ref="carbone_manuel"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

    <xs:element name="configuration">
    	<xs:complexType>
			<xs:sequence>
				<xs:element ref="typologie"/>
				<xs:element ref="implantation"/>
                <xs:element ref="parois"/>
                <xs:element ref="soubassement"/>
				<xs:element ref="menuiseries"/>
                <xs:element ref="fenetre_toit"/>
                <xs:element ref="plancher_bas"/>
				<xs:element ref="plancher_inter"/>
                <xs:element ref="combles"/>
                <xs:element ref="toitures-terrasses"/>
				<xs:element ref="autres"/>                
			</xs:sequence>
		</xs:complexType>
	</xs:element>
        <xs:element name="carbone_manuel">
    	<xs:complexType>
			<xs:sequence>
				<xs:element ref="carbone_data" maxOccurs="unbounded"/>              
			</xs:sequence>
		</xs:complexType>
	</xs:element>

    <xs:element name="date" type="xs:string"/>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="bbclic_version" type="xs:string"/>

    <xs:element name="general">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="date"/>
				<xs:element ref="description"/>
                <xs:element ref="bbclic_version"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

    <xs:element name="comboBox_ListeMaisons" type="xs:integer"/>
    <xs:element name="listeboxSysteme" type="xs:integer"/>
    <xs:element name="checkBox_BrasseurAir" type="xs:boolean"/>

    <xs:element name="typologie">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="comboBox_ListeMaisons"/>
				<xs:element ref="listeboxSysteme"/>
                <xs:element ref="checkBox_BrasseurAir"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

    <xs:element name="listeZoneClimatique" type="xs:integer"/>
    <xs:element name="comboBoxAltitude" type="xs:integer"/>
    <xs:element name="listeZoneDeBruit" type="xs:integer"/>
    <xs:element name="textBoxSaisieAngle" type="xs:string"/>

    <xs:element name="implantation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="listeZoneClimatique"/>
				<xs:element ref="comboBoxAltitude"/>
                <xs:element ref="listeZoneDeBruit"/>
                <xs:element ref="textBoxSaisieAngle"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>    

    <xs:element name="modeParoi" type="xs:boolean"/>
    <xs:element name="listeStructure" type="xs:integer"/>
    <xs:element name="listeTypeIsolant" type="xs:integer"/>
    <xs:element name="listeEpaisseurIsolant" type="xs:integer"/>
    <xs:element name="listeCouleurFacade" type="xs:integer"/>
    <xs:element name="valeurRStructure_avance" type="xs:string"/>
    <xs:element name="valeurRIsolant_avance" type="xs:string"/>
    <xs:element name="valeurCas_avance" type="xs:string"/>

    <xs:element name="parois">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="modeParoi"/>
				<xs:element ref="listeStructure"/>
                <xs:element ref="listeTypeIsolant"/>
                <xs:element ref="listeEpaisseurIsolant"/>
				<xs:element ref="listeCouleurFacade"/>
				<xs:element ref="valeurRStructure_avance"/>
                <xs:element ref="valeurRIsolant_avance"/>
                <xs:element ref="valeurCas_avance"/>                
			</xs:sequence>
		</xs:complexType>
	</xs:element> 

    <xs:element name="modeSoubassement" type="xs:boolean"/>
    <xs:element name="listeSoubassementStructure" type="xs:integer"/>
    <xs:element name="checkBoxIsolationRefend" type="xs:boolean"/>
    <xs:element name="textBoxRSoubassement" type="xs:string"/>
    <xs:element name="textBoxPsiPlancherBasRefend" type="xs:string"/>

    <xs:element name="soubassement">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="modeSoubassement"/>
				<xs:element ref="listeSoubassementStructure"/>
                <xs:element ref="checkBoxIsolationRefend"/>
                <xs:element ref="textBoxRSoubassement"/>
				<xs:element ref="textBoxPsiPlancherBasRefend"/>               
			</xs:sequence>
		</xs:complexType>
	</xs:element> 

    <xs:element name="listeMenuiseriesPerformance" type="xs:integer"/>
    <xs:element name="comboBoxChoixProtectionSolaire" type="xs:integer"/>
    <xs:element name="comboBoxModeGestion" type="xs:integer"/>
    <xs:element name="checkBoxMotorisation" type="xs:boolean"/>
    <xs:element name="checkBoxHorloge" type="xs:boolean"/>
    <xs:element name="listeUCoffretVR" type="xs:integer"/>

    <xs:element name="menuiseries">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="listeMenuiseriesPerformance"/>
				<xs:element ref="comboBoxChoixProtectionSolaire"/>
                <xs:element ref="comboBoxModeGestion"/>
                <xs:element ref="checkBoxMotorisation"/>
				<xs:element ref="checkBoxHorloge"/>
				<xs:element ref="listeUCoffretVR"/>               
			</xs:sequence>
		</xs:complexType>
	</xs:element> 

    <xs:element name="comboBoxChoixPMft" type="xs:integer"/>
    <xs:element name="comboBoxModeGestionFT" type="xs:integer"/>
    <xs:element name="checkBoxMotorisationFt" type="xs:boolean"/>

    <xs:element name="fenetre_toit">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="comboBoxChoixPMft"/>
				<xs:element ref="comboBoxModeGestionFT"/>
                <xs:element ref="checkBoxMotorisationFt"/>              
			</xs:sequence>
		</xs:complexType>
	</xs:element> 

    <xs:element name="modePlancherBas" type="xs:boolean"/>
    <xs:element name="listePbTypePlancher" type="xs:integer"/>
    <xs:element name="listePbComplementSur" type="xs:integer"/>
    <xs:element name="listePbRevetementSol" type="xs:integer"/>
    <xs:element name="listePbJonctionFacade" type="xs:integer"/>
    <xs:element name="textbox_UplancherBas_avance" type="xs:string"/>
    <xs:element name="textbox_Psil_PB_Facade" type="xs:string"/>

    <xs:element name="plancher_bas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="modePlancherBas"/>
				<xs:element ref="listePbTypePlancher"/>
                <xs:element ref="listePbComplementSur"/>
                <xs:element ref="listePbRevetementSol"/>
				<xs:element ref="listePbJonctionFacade"/>
				<xs:element ref="textbox_UplancherBas_avance"/>
                <xs:element ref="textbox_Psil_PB_Facade"/>              
			</xs:sequence>
		</xs:complexType>
	</xs:element> 

    <xs:element name="modePlancherInter" type="xs:boolean"/>
    <xs:element name="textBoxPsilPlancherIntermediaire" type="xs:string"/>
    <xs:element name="checkBox_PI_IsolationPeripheriqueFxPlafond" type="xs:string"/>
    <xs:element name="comboBox_PI_JonctionPlancherFacade" type="xs:integer"/>
    <xs:element name="comboBox_PI_RevetementSol" type="xs:integer"/>
    <xs:element name="comboBox_PI_EpaisseurPlancher" type="xs:integer"/>
    <xs:element name="comboBox_PI_TypePlancher" type="xs:integer"/>

    <xs:element name="plancher_inter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="modePlancherInter"/>
                <xs:element ref="comboBox_PI_TypePlancher"/>
				<xs:element ref="comboBox_PI_EpaisseurPlancher"/>
				<xs:element ref="comboBox_PI_RevetementSol"/>
                <xs:element ref="comboBox_PI_JonctionPlancherFacade"/>
				<xs:element ref="textBoxPsilPlancherIntermediaire"/>
                <xs:element ref="checkBox_PI_IsolationPeripheriqueFxPlafond"/>             
			</xs:sequence>
		</xs:complexType>
	</xs:element> 

    <xs:element name="modeToiture" type="xs:boolean"/>
    <xs:element name="listePhTypeIsolant" type="xs:integer"/>
    <xs:element name="listePhRIsolant" type="xs:integer"/>
    <xs:element name="textbox_RToiture_avance" type="xs:string"/>
    <xs:element name="textbox_PsiPlancherHautFacade_avance" type="xs:string"/>

    <xs:element name="combles">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="modeToiture"/>
				<xs:element ref="listePhTypeIsolant"/>
                <xs:element ref="listePhRIsolant"/>
                <xs:element ref="textbox_RToiture_avance"/>
				<xs:element ref="textbox_PsiPlancherHautFacade_avance"/>               
			</xs:sequence>
		</xs:complexType>
	</xs:element> 

    <xs:element name="checkBox_modeTT" type="xs:boolean"/>
    <xs:element name="comboBox_typePlancherTT" type="xs:integer"/>
    <xs:element name="comboBox_epaisseurPlancherTT" type="xs:integer"/>
    <xs:element name="comboBox_typeIsolationTT" type="xs:integer"/>
    <xs:element name="comboBox_epaisseurIsolationTT" type="xs:integer"/>
    <xs:element name="comboBox_TT_JonctionPlancherFacade" type="xs:integer"/>
    <xs:element name="checkBox_TT_IsolationPeripheriePlafond" type="xs:boolean"/>
    <xs:element name="comboBox_couleurTT" type="xs:integer"/>
    <xs:element name="checkBox_choixVegetalisationTT" type="xs:boolean"/>
    <xs:element name="textBox_TT_valeurUp" type="xs:string"/>
    <xs:element name="textBox_TT_valeurPsil" type="xs:string"/>
    <xs:element name="textBox_TT_valeurCAE" type="xs:string"/>
    <xs:element name="checkBox_TT_Veget_avance" type="xs:boolean"/>
    <xs:element name="textBox_TT_valeurSfe" type="xs:string"/>
    <xs:element name="textBox_TT_valeurSfc" type="xs:string"/>
    <xs:element name="dateTimePicker1" type="xs:string"/>
    <xs:element name="dateTimePicker2" type="xs:string"/>

    <xs:element name="toitures-terrasses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="checkBox_modeTT"/>
				<xs:element ref="comboBox_typePlancherTT"/>
                <xs:element ref="comboBox_epaisseurPlancherTT"/>
                <xs:element ref="comboBox_typeIsolationTT"/>
				<xs:element ref="comboBox_epaisseurIsolationTT"/>
				<xs:element ref="comboBox_TT_JonctionPlancherFacade"/>
                <xs:element ref="checkBox_TT_IsolationPeripheriePlafond"/>
                <xs:element ref="comboBox_couleurTT"/>
				<xs:element ref="checkBox_choixVegetalisationTT"/>
				<xs:element ref="textBox_TT_valeurUp"/>
                <xs:element ref="textBox_TT_valeurPsil"/>
                <xs:element ref="textBox_TT_valeurCAE"/>
				<xs:element ref="checkBox_TT_Veget_avance"/>
				<xs:element ref="textBox_TT_valeurSfe"/>
                <xs:element ref="textBox_TT_valeurSfc"/>
                <xs:element ref="dateTimePicker1"/>
                <xs:element ref="dateTimePicker2"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element> 

    <xs:element name="listeParametresTypeCloisonsInterieures" type="xs:integer"/>
    <xs:element name="listeParametresPermeabilitéAir" type="xs:integer"/>

    <xs:element name="autres">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="listeParametresTypeCloisonsInterieures"/>
				<xs:element ref="listeParametresPermeabilitéAir"/>              
			</xs:sequence>
		</xs:complexType>
	</xs:element>

    <xs:element name="itemValeurA" type="xs:string"/>
    <xs:element name="itemValeurB" type="xs:string"/>
    <xs:element name="itemValeurC" type="xs:string"/>
    <xs:element name="itemValeurD" type="xs:string"/>
    <xs:element name="itemValeurE" type="xs:string"/>

    <xs:element name="carbone_data">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="itemValeurA"/>
				<xs:element ref="itemValeurB"/>
                <xs:element ref="itemValeurC"/>
                <xs:element ref="itemValeurD"/>
				<xs:element ref="itemValeurE"/>               
			</xs:sequence>
            <xs:attribute name="parent" type="xs:string"/>
		</xs:complexType>
	</xs:element> 




</xs:schema>

=== pinkou78/bbclic2020_open/published/Application Files/BBClic® 2020_2_1_4_0/data/mapping_savefile_2.0.0.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./template_save.xsd">
  <general>
    <date></date>
    <description></description>
    <bbclic_version></bbclic_version>
  </general>
  <configuration>
    <typologie>
      <comboBox_ListeMaisons></comboBox_ListeMaisons>
      <listeboxSysteme></listeboxSysteme>
      <checkBox_BrasseurAir></checkBox_BrasseurAir>
    </typologie>
    <implantation>
      <listeZoneClimatique></listeZoneClimatique>
      <comboBoxAltitude></comboBoxAltitude>
      <listeZoneDeBruit></listeZoneDeBruit>
      <textBoxSaisieAngle></textBoxSaisieAngle>
    </implantation>
    <parois>
      <modeParoi></modeParoi>
      <listeStructure></listeStructure>
      <listeTypeIsolant></listeTypeIsolant>
      <listeEpaisseurIsolant></listeEpaisseurIsolant>
      <listeCouleurFacade></listeCouleurFacade>
      <valeurRStructure_avance></valeurRStructure_avance>
      <valeurRIsolant_avance></valeurRIsolant_avance>
      <valeurCas_avance></valeurCas_avance>
    </parois>
    <soubassement>
      <modeSoubassement></modeSoubassement>
      <listeSoubassementStructure></listeSoubassementStructure>
      <checkBoxIsolationRefend></checkBoxIsolationRefend>
      <textBoxRSoubassement></textBoxRSoubassement>
      <textBoxPsiPlancherBasRefend></textBoxPsiPlancherBasRefend>
    </soubassement>
    <menuiseries>
      <listeMenuiseriesPerformance></listeMenuiseriesPerformance>
      <comboBoxChoixProtectionSolaire></comboBoxChoixProtectionSolaire>
      <comboBoxModeGestion></comboBoxModeGestion>
      <checkBoxMotorisation></checkBoxMotorisation>
      <checkBoxHorloge></checkBoxHorloge>
      <listeUCoffretVR></listeUCoffretVR>
    </menuiseries>
    <fenetre_toit>
      <comboBoxChoixPMft></comboBoxChoixPMft>
      <comboBoxModeGestionFT></comboBoxModeGestionFT>
      <checkBoxMotorisationFt></checkBoxMotorisationFt>
    </fenetre_toit>
    <plancher_bas>
      <modePlancherBas></modePlancherBas>
      <listePbTypePlancher></listePbTypePlancher>
      <listePbComplementSur></listePbComplementSur>
      <listePbRevetementSol></listePbRevetementSol>
      <listePbJonctionFacade></listePbJonctionFacade>
      <textbox_UplancherBas_avance></textbox_UplancherBas_avance>
      <textbox_Psil_PB_Facade></textbox_Psil_PB_Facade>
    </plancher_bas>
    <plancher_inter>
      <modePlancherInter></modePlancherInter>
      <comboBox_PI_TypePlancher></comboBox_PI_TypePlancher>
      <comboBox_PI_EpaisseurPlancher></comboBox_PI_EpaisseurPlancher>
      <comboBox_PI_RevetementSol></comboBox_PI_RevetementSol>
      <comboBox_PI_JonctionPlancherFacade></comboBox_PI_JonctionPlancherFacade>
      <checkBox_PI_IsolationPeripheriqueFxPlafond></checkBox_PI_IsolationPeripheriqueFxPlafond>
      <textBoxPsilPlancherIntermediaire></textBoxPsilPlancherIntermediaire>
    </plancher_inter>
    <combles>
      <modeToiture></modeToiture>
      <listePhTypeIsolant></listePhTypeIsolant>
      <listePhRIsolant></listePhRIsolant>
      <textbox_RToiture_avance></textbox_RToiture_avance>
      <textbox_PsiPlancherHautFacade_avance></textbox_PsiPlancherHautFacade_avance>
    </combles>
    <toitures-terrasses>
      <checkBox_modeTT></checkBox_modeTT>
      <comboBox_typePlancherTT></comboBox_typePlancherTT>
      <comboBox_epaisseurPlancherTT></comboBox_epaisseurPlancherTT>
      <comboBox_typeIsolationTT></comboBox_typeIsolationTT>
      <comboBox_epaisseurIsolationTT></comboBox_epaisseurIsolationTT>
      <comboBox_TT_JonctionPlancherFacade></comboBox_TT_JonctionPlancherFacade>
      <checkBox_TT_IsolationPeripheriePlafond></checkBox_TT_IsolationPeripheriePlafond>
      <comboBox_couleurTT></comboBox_couleurTT>
      <checkBox_choixVegetalisationTT></checkBox_choixVegetalisationTT>
      <textBox_TT_valeurUp></textBox_TT_valeurUp>
      <textBox_TT_valeurPsil></textBox_TT_valeurPsil>
      <textBox_TT_valeurCAE></textBox_TT_valeurCAE>
      <checkBox_TT_Veget_avance></checkBox_TT_Veget_avance>
      <textBox_TT_valeurSfe></textBox_TT_valeurSfe>
      <textBox_TT_valeurSfc></textBox_TT_valeurSfc>
      <dateTimePicker1></dateTimePicker1>
      <dateTimePicker2></dateTimePicker2>
    </toitures-terrasses>
    <autres>
      <listeParametresTypeCloisonsInterieures></listeParametresTypeCloisonsInterieures>
      <listeParametresPermeabilitéAir></listeParametresPermeabilitéAir>
    </autres>
  </configuration>
  <carbone_manuel>
    <carbone_data parent="saisieCarboneStructureParoi">
      <itemValeurA></itemValeurA>
      <itemValeurB></itemValeurB>
      <itemValeurC></itemValeurC>
      <itemValeurD></itemValeurD>
      <itemValeurE></itemValeurE>
    </carbone_data>
    <carbone_data parent="saisieCarboneIsolationParoi">
      <itemValeurA></itemValeurA>
      <itemValeurB></itemValeurB>
      <itemValeurC></itemValeurC>
      <itemValeurD></itemValeurD>
      <itemValeurE></itemValeurE>
    </carbone_data>
      <carbone_data parent="saisieCarboneStructureSoubassement">
      <itemValeurA></itemValeurA>
      <itemValeurB></itemValeurB>
      <itemValeurC></itemValeurC>
      <itemValeurD></itemValeurD>
      <itemValeurE></itemValeurE>
    </carbone_data>
      <carbone_data parent="saisieCarbonePlancherBas">
      <itemValeurA></itemValeurA>
      <itemValeurB></itemValeurB>
      <itemValeurC></itemValeurC>
      <itemValeurD></itemValeurD>
      <itemValeurE></itemValeurE>
    </carbone_data>
      <carbone_data parent="saisieCarboneIsolationPB">
      <itemValeurA></itemValeurA>
      <itemValeurB></itemValeurB>
      <itemValeurC></itemValeurC>
      <itemValeurD></itemValeurD>
      <itemValeurE></itemValeurE>
    </carbone_data>
      <carbone_data parent="saisieCarboneChapePB">
      <itemValeurA></itemValeurA>
      <itemValeurB></itemValeurB>
      <itemValeurC></itemValeurC>
      <itemValeurD></itemValeurD>
      <itemValeurE></itemValeurE>
    </carbone_data>
      <carbone_data parent="saisieCarboneRevetementPB">
      <itemValeurA></itemValeurA>
      <itemValeurB></itemValeurB>
      <itemValeurC></itemValeurC>
      <itemValeurD></itemValeurD>
      <itemValeurE></itemValeurE>
    </carbone_data>
      <carbone_data parent="saisieCarboneComble">
      <itemValeurA></itemValeurA>
      <itemValeurB></itemValeurB>
      <itemValeurC></itemValeurC>
      <itemValeurD></itemValeurD>
      <itemValeurE></itemValeurE>
    </carbone_data>
  </carbone_manuel>
</root>
