=== pinkou78/bbclic2020_open/published/Application Files/BBClic® 2020_2_1_4_0/data/bbclic_carbone.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="Maison_ID" type="xs:integer"/>
	<xs:element name="Produit_GUID" type="xs:string"/>
	<xs:element name="Nom" type="xs:string"/>
	<xs:element name="Type" type="xs:string"/>
	<xs:element name="Lot" type="xs:integer"/>
	<xs:element name="Valeur" type="xs:decimal"/>
	<xs:element name="numero" type="xs:integer"/>
	<xs:element name="part_fixe" type="xs:decimal"/>
	<xs:element name="identification" type="xs:string"/>
	<xs:element name="texte" type="xs:string"/>

	<xs:element name="Ic_Lot">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="numero"/>
				<xs:element ref="part_fixe"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Ic_composants">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Ic_Lot" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="indicateur">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Nom"/>
				<xs:element ref="Valeur"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="indicateurs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Lot"/>
				<xs:element ref="indicateur" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Indicateurs_Collection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="indicateurs" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Produit">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Produit_GUID"/>
				<xs:element ref="Nom"/>
				<xs:element ref="Type"/>
				<xs:element ref="Indicateurs_Collection"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Produit_Collection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Produit" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Maison">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Maison_ID"/>
				<xs:element ref="Nom"/>
				<xs:element ref="Produit_Collection"/>
				<xs:element ref="Ic_composants"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Maison_Collection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Maison" maxOccurs="unbounded"/>

			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<xs:element name="carbone">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Maison_Collection" maxOccurs="unbounded"/>
				<xs:element ref="Dictionnaire"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Dictionnaire">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="item" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>	
	</xs:element>
	
	<xs:element name="item">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="identification"/>
				<xs:element ref="texte"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


</xs:schema>

=== pinkou78/bbclic2020_open/published/Application Files/BBClic® 2020_2_1_0_0/data/bbclic_data_carbone_v2.xml
<?xml version="1.0" encoding="utf-8"?>
<carbone xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bbclic_carbone.xsd">
	<Maison_Collection>
		<Maison>
			<Maison_ID>0</Maison_ID>
			<Nom>Maison de plain-pied avec combles perdus</Nom>
			<Produit_Collection>
				<Produit>
					<Produit_GUID>6F8CB49C-41B5-4B28-ADA5-2B244518AC19</Produit_GUID>
					<Nom>R = 0,23 m2.K/W (ex. Bloc creux de granulats courant - Maçonné B40)</Nom>
					<Type>Paroi</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>2</Lot>
							<indicateur>
								<Nom></Nom>
								<Valeur>3.86</Valeur>
							</indicateur>
						</indicateurs>
						<indicateurs>
							<Lot>3</Lot>
							<indicateur>
								<Nom></Nom>
								<Valeur>17.636</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>2C76BFA8-DA46-4698-B334-A5216A60FC9E</Produit_GUID>
					<Nom>R = 0,29 m2.K/W (ex. Bloc creux de granulats courant - Collé B40)</Nom>
					<Type>Paroi</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>2</Lot>
							<indicateur>
								<Nom></Nom>
								<Valeur>2.64</Valeur>
							</indicateur>
						</indicateurs>
						<indicateurs>
							<Lot>3</Lot>
							<indicateur>
								<Nom></Nom>
								<Valeur>12.0417</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>D7859845-4B5D-46CB-A19B-5FC9D4C3DBF3</Produit_GUID>
					<Nom>R = 0,23 m2.K/W (ex. Bloc creux de granulats courant - Maçonné B60)</Nom>
					<Type>Paroi</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>2</Lot>
							<indicateur>
								<Nom></Nom>
								<Valeur>4.34</Valeur>
							</indicateur>
						</indicateurs>
						<indicateurs>
							<Lot>3</Lot>
							<indicateur>
								<Nom></Nom>
								<Valeur>19.79</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>68FD2FF6-3546-43B5-A2B0-D097E6DC9335</Produit_GUID>
					<Nom>R = 0,29 m2.K/W (ex. Bloc creux de granulats courant - Collé B60)</Nom>
					<Type>Paroi</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>2</Lot>
							<indicateur>
								<Nom></Nom>
								<Valeur>3.39</Valeur>
							</indicateur>
						</indicateurs>
						<indicateurs>
							<Lot>3</Lot>
							<indicateur>
								<Nom></Nom>
								<Valeur>15.46</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>641EBBB4-8D95-4A83-ABA5-E33B5BCCDC2B</Produit_GUID>
					<Nom>Doublage sur ossature laine de verre (λ = 0,032 W/(m.K))</Nom>
					<Type>Isolation Paroi</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>5</Lot>
							<indicateur>
								<Nom>0.08</Nom>
								<Valeur>5.00</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.10</Nom>
								<Valeur>5.68</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.12</Nom>
								<Valeur>6.06</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.14</Nom>
								<Valeur>6.48</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.16</Nom>
								<Valeur>6.84</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>5884E78A-A9F4-4AD4-900C-E72D5D9ECCAF</Produit_GUID>
					<Nom>Doublage collé PSE (λ = 0,032 W/(m.K))</Nom>
					<Type>Isolation Paroi</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>5</Lot>
							<indicateur>
								<Nom>0.08</Nom>
								<Valeur>4.16</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.10</Nom>
								<Valeur>4.85</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.12</Nom>
								<Valeur>5.51</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.14</Nom>
								<Valeur>6.15</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.16</Nom>
								<Valeur>6.78</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>D77765BB-B2DC-4A60-BE2E-9F721BFB8E9B</Produit_GUID>
					<Nom>Doublage collé PSE (λ = 0,030 W/(m.K))</Nom>
					<Type>Isolation Paroi</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>5</Lot>
							<indicateur>
								<Nom>0.08</Nom>
								<Valeur>6.48</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.10</Nom>
								<Valeur>7.42</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.12</Nom>
								<Valeur>8.36</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.14</Nom>
								<Valeur>9.29</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.16</Nom>
								<Valeur>10.17</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>328ACC72-D7E5-49DE-A9DD-37D7C70A97BA</Produit_GUID>
					<Nom>Doublage collé Polyuréthane (λ = 0,022 W/(m.K))</Nom>
					<Type>Isolation Paroi</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>5</Lot>
							<indicateur>
								<Nom>0.08</Nom>
								<Valeur>8.32</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.10</Nom>
								<Valeur>12.08</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.12</Nom>
								<Valeur>14.09</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.14</Nom>
								<Valeur>14.44</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.16</Nom>
								<Valeur>15.78</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>4AAA6794-88C4-4885-B141-FFF504D121D9</Produit_GUID>
					<Nom>Doublage collé laine de roche (λ = 0,036 W/(m.K))</Nom>
					<Type>Isolation Paroi</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>5</Lot>
							<indicateur>
								<Nom>0.08</Nom>
								<Valeur>4.67</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.10</Nom>
								<Valeur>5.15</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.12</Nom>
								<Valeur>5.65</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.14</Nom>
								<Valeur>6.15</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.16</Nom>
								<Valeur>6.63</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>58C61547-3E45-49D9-8593-876BCC762B96</Produit_GUID>
					<Nom>Doublage sur ossature fibre de bois (λ = 0,038 W/(m.K))</Nom>
					<Type>Isolation Paroi</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>5</Lot>
							<indicateur>
								<Nom>0.08</Nom>
								<Valeur>2.80</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.10</Nom>
								<Valeur>2.81</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.12</Nom>
								<Valeur>2.81</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.14</Nom>
								<Valeur>2.82</Valeur>
							</indicateur>
							<indicateur>
								<Nom>0.16</Nom>
								<Valeur>2.83</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>FCC99363-B8B8-4227-B046-F757F2DC92A7</Produit_GUID>
					<Nom>Isolation du refend de soubassement</Nom>
					<Type>Isolation soubassement</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>2</Lot>
							<indicateur>
								<Nom></Nom>
								<Valeur>0.70</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>D54FE3D1-88A1-4C4D-B13F-19A160A5B874</Produit_GUID>
					<Nom>Dalle béton pleine 16cm sur VS</Nom>
					<Type>Plancher bas</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>3</Lot>
							<indicateur>
								<Nom></Nom>
								<Valeur>54.8508</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>93D84CA5-B17C-4ACF-8906-A7FD7D0A5A0A</Produit_GUID>
					<Nom>Entrevous béton 12+4</Nom>
					<Type>Plancher bas</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>3</Lot>
							<indicateur>
								<Nom></Nom>
								<Valeur>37.4022</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>162D9A10-FF82-4AA7-9C57-C67987CC479D</Produit_GUID>
					<Nom>Entrevous PSE 12+5 - Up= 0.27 W/(m².K)</Nom>
					<Type>Plancher bas</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>3</Lot>
							<indicateur>
								<Nom></Nom>
								<Valeur>47.9672</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>223A3221-DA6E-4AA2-BD69-4CB12357468D</Produit_GUID>
					<Nom>Entrevous PSE 12+5 - Up= 0.23 W/(m².K)</Nom>
					<Type>Plancher bas</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>3</Lot>
							<indicateur>
								<Nom></Nom>
								<Valeur>50.4374</Valeur>
							</indicateur>
						</indicateurs>
					</Indicateurs_Collection>
				</Produit>
				<Produit>
					<Produit_GUID>3FDBE679-77EC-47DC-AB71-E7AC96F52FD4</Produit_GUID>
					<Nom>Entrevous PSE 12+5 - Up= 0.19 W/(m².K)</Nom>
					<Type>Plancher bas</Type>
					<Indicateurs_Collection>
						<indicateurs>
							<Lot>3</Lot>
							<indicateur>
								<Nom></Nom>
